name: Publsh to PyPi
on:
  pull_request:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # cache pip dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine bump2version
      - name: Bump version number
        uses: Clinical-Genomics/bump2version-ci@v3
        env:
          BUMPVERSION_AUTHOR: panmlbot
          BUMPVERSION_EMAIL: teampanml@gmail.com
          BUMPVERSION_TOKEN: ${{ secrets.BOT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        env:
          name: pypi
          url: https://pypi.org/project/panml/
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
