name: Publsh to PyPi
on:
  pull_request:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # cache pip dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine bump2version
      - name: Bump version number
        env:
          BOT_USERNAME: panmlbot
          BOT_EMAIL: teampanml@gmail.com
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          set -x
          git config --global user.name "${BOT_USERNAME}"
          git config --global user.email "${BOT_EMAIL}"
          git config --global pull.rebase false
          BRANCH=${GITHUB_REF#refs/heads/}
          git remote add ${BOT_USERNAME} https://${BOT_USERNAME}:${BOT_TOKEN}@github.com/$GITHUB_REPOSITORY
          git pull --no-edit ${BOT_USERNAME} $BRANCH
          bump2version minor
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          branch: ${{ github.ref }}
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        env:
          name: pypi
          url: https://pypi.org/project/panml/
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
